VALIDATION_OK = 0
VALIDATION_NOT_SETUP = 1
VALIDATION_NEED_UPGRADE = 2
VALIDATION_ERROR = 255

GROUP_BY_NONE = 0
GROUP_BY_SUM = 1
GROUP_BY_AVERAGE = 2
GROUP_BY_MEDIAN = 3

from MariaDB import MariaDB

